//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BibliotecaDBEntities : DbContext
    {
        public BibliotecaDBEntities()
            : base("name=BibliotecaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Editorial> Editorial { get; set; }
        public virtual DbSet<Libro> Libro { get; set; }
    
        public virtual int AddLibro(string titulo, Nullable<System.DateTime> añoPublicacion, Nullable<int> idAutor, Nullable<int> idEditorial)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            var añoPublicacionParameter = añoPublicacion.HasValue ?
                new ObjectParameter("AñoPublicacion", añoPublicacion) :
                new ObjectParameter("AñoPublicacion", typeof(System.DateTime));
    
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddLibro", tituloParameter, añoPublicacionParameter, idAutorParameter, idEditorialParameter);
        }
    
        public virtual int BorrarLibroPorEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("BorrarLibroPorEditorial", idEditorialParameter);
        }
    
        public virtual int DeleteLibros(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLibros", idAutorParameter);
        }
    
        public virtual ObjectResult<LibroPorAutor_Result> LibroPorAutor(Nullable<int> idAutor)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroPorAutor_Result>("LibroPorAutor", idAutorParameter);
        }
    
        public virtual ObjectResult<LibroPorEditorial_Result> LibroPorEditorial(Nullable<int> idEditorial)
        {
            var idEditorialParameter = idEditorial.HasValue ?
                new ObjectParameter("IdEditorial", idEditorial) :
                new ObjectParameter("IdEditorial", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibroPorEditorial_Result>("LibroPorEditorial", idEditorialParameter);
        }
    
        public virtual ObjectResult<LibrosPorFecha_Result> LibrosPorFecha(Nullable<System.DateTime> añoPublicacion)
        {
            var añoPublicacionParameter = añoPublicacion.HasValue ?
                new ObjectParameter("AñoPublicacion", añoPublicacion) :
                new ObjectParameter("AñoPublicacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibrosPorFecha_Result>("LibrosPorFecha", añoPublicacionParameter);
        }
    
        public virtual ObjectResult<LibrosPorFechaYHora_Result> LibrosPorFechaYHora(Nullable<int> idAutor, Nullable<System.DateTime> añoPublicacion)
        {
            var idAutorParameter = idAutor.HasValue ?
                new ObjectParameter("IdAutor", idAutor) :
                new ObjectParameter("IdAutor", typeof(int));
    
            var añoPublicacionParameter = añoPublicacion.HasValue ?
                new ObjectParameter("AñoPublicacion", añoPublicacion) :
                new ObjectParameter("AñoPublicacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibrosPorFechaYHora_Result>("LibrosPorFechaYHora", idAutorParameter, añoPublicacionParameter);
        }
    
        public virtual ObjectResult<LibrosPorTitulo_Result> LibrosPorTitulo(string titulo)
        {
            var tituloParameter = titulo != null ?
                new ObjectParameter("Titulo", titulo) :
                new ObjectParameter("Titulo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LibrosPorTitulo_Result>("LibrosPorTitulo", tituloParameter);
        }
    }
}
